exclude: |
  (?x)
  # NOT INSTALLABLE ADDONS
  ^delivery_carrier_preference/|
  ^delivery_carrier_warehouse/|
  ^delivery_preference_glue_stock_picking_group/|
  ^sale_stock_available_to_promise_release/|
  ^shopfloor/|
  ^shopfloor_base/|
  ^shopfloor_batch_automatic_creation/|
  ^shopfloor_checkout_sync/|
  ^shopfloor_mobile/|
  ^shopfloor_mobile_custom_example/|
  ^shopfloor_packing_info/|
  ^shopfloor_rest_log/|
  ^shopfloor_workstation/|
  ^stock_available_to_promise_release/|
  ^stock_available_to_promise_release_dynamic_routing/|
  ^stock_checkout_sync/|
  ^stock_dynamic_routing/|
  ^stock_dynamic_routing_checkout_sync/|
  ^stock_dynamic_routing_reserve_rule/|
  ^stock_move_source_relocate/|
  ^stock_move_source_relocate_dynamic_routing/|
  ^stock_picking_type_shipping_policy/|
  ^stock_picking_type_shipping_policy_group_by/|
  ^stock_reception_screen/|
  ^stock_storage_type_buffer/|
  ^stock_storage_type_putaway_abc/|
  # END NOT INSTALLABLE ADDONS
  # Files and folders generated by bots, to avoid loops
  ^setup/|/static/description/index\.html$|
  # We don't want to mess with tool-generated files
  .svg$|
  # Maybe reactivate this when all README files include prettier ignore tags?
  ^README\.md$|
  # Library files can have extraneous formatting (even minimized)
  lib/|
  # Repos using Sphinx to generate docs don't need prettying
  ^docs/_templates/.*\.html$|
  # You don't usually want a bot to modify your legal texts
  (LICENSE.*|COPYING.*)
default_language_version:
  python: python3
  node: "14.13.0"
repos:
  - repo: local
    hooks:
      # These files are most likely copier diff rejection junks; if found,
      # review them manually, fix the problem (if needed) and remove them
      - id: forbidden-files
        name: forbidden files
        entry: found forbidden files; remove them
        language: fail
        files: "\\.rej$"
  - repo: https://github.com/oca/maintainer-tools
    rev: ab1d7f6
    hooks:
      # update the NOT INSTALLABLE ADDONS section above
      - id: oca-update-pre-commit-excluded-addons
      - id: oca-fix-manifest-website
        args: ["https://github.com/OCA/wms"]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ["-i", "--ignore-init-module-imports"]
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v1.19.1
    hooks:
      - id: prettier
        name: prettier (with plugin-xml)
        entry: prettier --write --list-different
        additional_dependencies:
          - "prettier@1.19.1"
          - "@prettier/plugin-xml@0.7.2"
        files: \.(css|htm|html|js|json|jsx|less|md|scss|toml|ts|xml|yaml|yml)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.8.0
    hooks:
      - id: eslint
        verbose: true
        args:
          - --color
          - --fix
        # SPECIAL CASE: barcode scanner app use Vue.js +
        # advanced JS (modules, classes, etc)
        # which are not supported by OCA rules yet.
        exclude: shopfloor_mobile*/*
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: debug-statements
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        # exclude files where underlines are not distinguishable from merge conflicts
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.26.2
    hooks:
      - id: pyupgrade
        args: ["--keep-percent-format"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        name: isort except __init__.py
        exclude: /__init__\.py$
  - repo: https://github.com/acsone/setuptools-odoo
    rev: 2.5.2
    hooks:
      - id: setuptools-odoo-make-default
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        name: flake8 except __init__.py
        exclude: /__init__\.py$
      - id: flake8
        name: flake8 only __init__.py
        args: ["--extend-ignore=F401"] # ignore unused imports in __init__.py
        files: /__init__\.py$
        language_version: python2.7
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.5.3
    hooks:
      - id: pylint
        name: pylint with optional checks
        args:
          - --rcfile=.pylintrc
          - --exit-zero
        verbose: true
        additional_dependencies: &pylint_deps
          - pylint-odoo==3.5.0
      - id: pylint
        name: pylint with mandatory checks
        args:
          - --rcfile=.pylintrc-mandatory
        additional_dependencies: *pylint_deps
