name: shopfloor app unit tests

on: [push, pull_request]

defaults:
  run:
    working-directory: shopfloor_ui_tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm run unit-tests
