from . import test_start
from . import test_select_document
from . import test_manual_selection
from . import test_select_move
from . import test_reception_done
from . import test_set_lot
from . import test_set_lot_confirm
from . import test_set_quantity
from . import test_set_quantity_action
from . import test_set_destination
from . import test_select_dest_package
from . import test_return_scan_document
from . import test_return_scan_line
from . import test_return_set_quantity
from . import test_return_reception_done
